version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=sample_db
    restart: always
    volumes:
      - db-data:/data/db:delegated

volumes:
  db-data:
